"""Precinct — persistence. Dual-backend behind one tiny API:
SQLite by default (file, zero setup) · Postgres when PRECINCT_PG_* env is present
(Cloud SQL over the mounted unix socket in prod). api.py/auth.py never know which.

Env (PG mode):
  PRECINCT_PG_SOCKET  /cloudsql/<project:region:instance>   (prod path)
  PRECINCT_PG_HOST/PRECINCT_PG_PORT                          (tcp alternative)
  PRECINCT_PG_DB · PRECINCT_PG_USER · PRECINCT_PG_PASSWORD
Tests may replace `_connect_pg_factory` (see tests/conftest.py) to reach a test DB.
"""
from __future__ import annotations

import json
import os
import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path

_DB_PATH = os.environ.get("PRECINCT_DB", str(Path(__file__).resolve().parent.parent / "precinct.db"))
_lock = threading.Lock()
_conn = None
_is_pg = False


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _pg_env() -> dict | None:
    sock = os.environ.get("PRECINCT_PG_SOCKET", "").strip()
    host = os.environ.get("PRECINCT_PG_HOST", "").strip()
    if not (sock or host):
        return None
    return {"sock": sock, "host": host, "port": int(os.environ.get("PRECINCT_PG_PORT", "5432") or 5432),
            "db": os.environ.get("PRECINCT_PG_DB", "precinct"),
            "user": os.environ.get("PRECINCT_PG_USER", "precinct_app"),
            "pw": os.environ.get("PRECINCT_PG_PASSWORD", "")}


def _connect_pg_factory():
    """Build a pg8000 connection from env. Tests may monkeypatch this."""
    import pg8000.dbapi as pgd
    p = _pg_env()
    if p["sock"]:
        return pgd.connect(unix_sock=p["sock"] + "/.s.PGSQL.5432", user=p["user"],
                           password=p["pw"], database=p["db"])
    return pgd.connect(host=p["host"], port=p["port"], user=p["user"],
                       password=p["pw"], database=p["db"])


_DDL_COMMON_TABLES = [
    ("campaigns", "id {IDENT}, name TEXT, office_type TEXT, created TEXT"),
    ("voter_tags", "campaign_id INT, voter_id TEXT, tag TEXT, created TEXT, UNIQUE(campaign_id,voter_id,tag)"),
    ("lists", "id {IDENT}, campaign_id INT, name TEXT, query TEXT, voter_ids TEXT, count INT, created TEXT"),
    ("contributions", "id {IDENT}, campaign_id INT, donor_name TEXT, amount TEXT, date TEXT, phase TEXT, "
                      "method TEXT, address TEXT, check_number TEXT, provenance TEXT, created TEXT"),
    ("expenses", "id {IDENT}, campaign_id INT, payee TEXT, amount TEXT, date TEXT, purpose TEXT, provenance TEXT, created TEXT"),
    ("audit", "id {IDENT}, campaign_id INT, action TEXT, detail TEXT, created TEXT"),
    ("users", "id {IDENT}, email TEXT UNIQUE, name TEXT, pw_hash TEXT, salt TEXT, role TEXT, created TEXT"),
    ("sessions", "token_hash TEXT UNIQUE, user_id INT, expires TEXT, created TEXT"),
    ("memberships", "user_id INT, campaign_id INT, role TEXT, created TEXT, UNIQUE(user_id,campaign_id)"),
]


def _init_schema(c):
    ident = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if _is_pg else "INTEGER PRIMARY KEY AUTOINCREMENT"
    for name, cols in _DDL_COMMON_TABLES:
        stmt = f"CREATE TABLE IF NOT EXISTS {name}({cols.format(IDENT=ident)})"
        if _is_pg:
            cur = c.cursor(); cur.execute(stmt); cur.close()
        else:
            c.execute(stmt)
    if not _is_pg:
        c.commit()


def conn():
    global _conn, _is_pg
    if _conn is None:
        if _pg_env():
            _is_pg = True
            _conn = _connect_pg_factory()
            _conn.autocommit = True
        else:
            _is_pg = False
            _conn = sqlite3.connect(_DB_PATH, check_same_thread=False)
            _conn.row_factory = sqlite3.Row
        _init_schema(_conn)
    return _conn


def _reset_connection():
    global _conn
    try:
        if _conn is not None:
            _conn.close()
    except Exception:
        pass
    _conn = None


def _fix(sql: str) -> str:
    return sql.replace("?", "%s") if _is_pg else sql


def q(sql: str, args=()) -> list[dict]:
    """SELECT → list of dicts. One retry on a dropped PG connection (Cloud Run idle)."""
    for attempt in (1, 2):
        try:
            with _lock:
                c = conn()
                if _is_pg:
                    cur = c.cursor()
                    cur.execute(_fix(sql), tuple(args))
                    cols = [d[0] for d in cur.description]
                    out = [dict(zip(cols, r)) for r in cur.fetchall()]
                    cur.close()
                    return out
                return [dict(r) for r in c.execute(sql, args).fetchall()]
        except Exception:
            if attempt == 2 or not _is_pg:
                raise
            _reset_connection()


def _write(sql: str, args=(), want_id: bool = False):
    for attempt in (1, 2):
        try:
            with _lock:
                c = conn()
                if _is_pg:
                    s = _fix(sql) + (" RETURNING id" if want_id else "")
                    cur = c.cursor()
                    cur.execute(s, tuple(args))
                    rid = cur.fetchone()[0] if want_id else None
                    cur.close()
                    return rid
                cur = c.execute(sql, args)
                c.commit()
                return cur.lastrowid
        except Exception:
            if attempt == 2 or not _is_pg:
                raise
            _reset_connection()


# --- campaigns ---
def create_campaign(name: str, office_type: str = "other") -> int:
    return _write("INSERT INTO campaigns(name,office_type,created) VALUES(?,?,?)", (name, office_type, _now()), want_id=True)

def list_campaigns() -> list[dict]:
    return q("SELECT * FROM campaigns ORDER BY id")

def get_campaign(cid: int) -> dict | None:
    r = q("SELECT * FROM campaigns WHERE id=?", (cid,))
    return r[0] if r else None


# --- voter tags (CRM + canvass capture) ---
def add_tag(cid: int, voter_id: str, tag: str):
    if _is_pg:
        _write("INSERT INTO voter_tags(campaign_id,voter_id,tag,created) VALUES(?,?,?,?) ON CONFLICT DO NOTHING",
               (cid, voter_id, tag, _now()))
    else:
        _write("INSERT OR IGNORE INTO voter_tags(campaign_id,voter_id,tag,created) VALUES(?,?,?,?)",
               (cid, voter_id, tag, _now()))

def remove_tag(cid: int, voter_id: str, tag: str):
    _write("DELETE FROM voter_tags WHERE campaign_id=? AND voter_id=? AND tag=?", (cid, voter_id, tag))

def tags_for_voter(cid: int, voter_id: str) -> list[str]:
    return [r["tag"] for r in q("SELECT tag FROM voter_tags WHERE campaign_id=? AND voter_id=?", (cid, voter_id))]

def tagged_voters(cid: int, tag: str | None = None) -> list[dict]:
    if tag:
        return q("SELECT voter_id,tag FROM voter_tags WHERE campaign_id=? AND tag=?", (cid, tag))
    return q("SELECT voter_id,tag FROM voter_tags WHERE campaign_id=?", (cid,))

def tag_counts(cid: int) -> dict:
    return {r["tag"]: r["n"] for r in q("SELECT tag,COUNT(*) AS n FROM voter_tags WHERE campaign_id=? GROUP BY tag", (cid,))}


# --- saved lists / turf ---
def save_list(cid: int, name: str, query: str, voter_ids: list[str]) -> int:
    return _write("INSERT INTO lists(campaign_id,name,query,voter_ids,count,created) VALUES(?,?,?,?,?,?)",
                  (cid, name, query, json.dumps(voter_ids), len(voter_ids), _now()), want_id=True)

def get_lists(cid: int) -> list[dict]:
    return [{**r, "voter_ids": json.loads(r["voter_ids"])}
            for r in q("SELECT * FROM lists WHERE campaign_id=? ORDER BY id DESC", (cid,))]

def get_list(lid: int) -> dict | None:
    r = q("SELECT * FROM lists WHERE id=?", (lid,))
    if not r:
        return None
    d = r[0]
    d["voter_ids"] = json.loads(d["voter_ids"])
    return d


# --- finance ---
def add_contribution(cid: int, **f) -> int:
    return _write("INSERT INTO contributions(campaign_id,donor_name,amount,date,phase,method,address,check_number,provenance,created) VALUES(?,?,?,?,?,?,?,?,?,?)",
                  (cid, f["donor_name"], f["amount"], f["date"], f["phase"], f["method"],
                   f.get("address", ""), f.get("check_number", ""), f.get("provenance", "entered"), _now()), want_id=True)

def get_contributions(cid: int) -> list[dict]:
    return q("SELECT * FROM contributions WHERE campaign_id=? ORDER BY id", (cid,))

def add_expense(cid: int, payee: str, amount: str, date: str, purpose: str, provenance: str = "entered") -> int:
    return _write("INSERT INTO expenses(campaign_id,payee,amount,date,purpose,provenance,created) VALUES(?,?,?,?,?,?,?)",
                  (cid, payee, amount, date, purpose, provenance, _now()), want_id=True)

def get_expenses(cid: int) -> list[dict]:
    return q("SELECT * FROM expenses WHERE campaign_id=? ORDER BY id", (cid,))


# --- users / sessions / memberships (auth; dark until PRECINCT_AUTH=1) ---
def count_users() -> int:
    return q("SELECT COUNT(*) AS n FROM users")[0]["n"]

def create_user(email: str, name: str, pw_hash: str, salt: str, role: str) -> int:
    return _write("INSERT INTO users(email,name,pw_hash,salt,role,created) VALUES(?,?,?,?,?,?)",
                  (email, name, pw_hash, salt, role, _now()), want_id=True)

def get_user_by_email(email: str) -> dict | None:
    r = q("SELECT * FROM users WHERE email=?", (email,))
    return r[0] if r else None

def create_session(token_hash: str, user_id: int, expires: str):
    if _is_pg:
        _write("INSERT INTO sessions(token_hash,user_id,expires,created) VALUES(?,?,?,?) "
               "ON CONFLICT (token_hash) DO UPDATE SET user_id=EXCLUDED.user_id, expires=EXCLUDED.expires, created=EXCLUDED.created",
               (token_hash, user_id, expires, _now()))
    else:
        _write("INSERT OR REPLACE INTO sessions(token_hash,user_id,expires,created) VALUES(?,?,?,?)",
               (token_hash, user_id, expires, _now()))

def get_session_user(token_hash: str) -> dict | None:
    r = q("SELECT u.id,u.email,u.name,u.role,s.expires FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=?",
          (token_hash,))
    return r[0] if r else None

def delete_session(token_hash: str):
    _write("DELETE FROM sessions WHERE token_hash=?", (token_hash,))

def add_membership(user_id: int, campaign_id: int, role: str = "manager"):
    if _is_pg:
        _write("INSERT INTO memberships(user_id,campaign_id,role,created) VALUES(?,?,?,?) ON CONFLICT DO NOTHING",
               (user_id, campaign_id, role, _now()))
    else:
        _write("INSERT OR IGNORE INTO memberships(user_id,campaign_id,role,created) VALUES(?,?,?,?)",
               (user_id, campaign_id, role, _now()))

def get_membership(user_id: int, campaign_id: int) -> dict | None:
    r = q("SELECT * FROM memberships WHERE user_id=? AND campaign_id=?", (user_id, campaign_id))
    return r[0] if r else None

def memberships_for_user(user_id: int) -> list[dict]:
    return q("SELECT campaign_id,role FROM memberships WHERE user_id=?", (user_id,))


# --- audit trail (every write, compliance posture) ---
def log_action(cid: int, action: str, detail: str = ""):
    _write("INSERT INTO audit(campaign_id,action,detail,created) VALUES(?,?,?,?)", (cid, action, (detail or "")[:300], _now()))

def get_audit(cid: int, limit: int = 20) -> list[dict]:
    limit = max(1, min(int(limit), 100))
    return q("SELECT action,detail,created FROM audit WHERE campaign_id=? ORDER BY id DESC LIMIT ?", (cid, limit))
